### ISSUE TITLE
File store that is agnostic 

### ISSUE THREAD

**Issue by gedw99** [richardartoul/nola#55]
https://github.com/hack-pad/hackpadfs

Will allow an actors to run in browsers or on servers ( Wazero etc  or golang ). Fits Nola perspectives …

Indexdb in a browser can be garbage collected at any time by the OS . So you can use it expecting it to always there 

It can also call out to S3 buckets 

See examples :) 

With a nats kv server feeding it , it can always catchup off local OS, Intranet ( NATS leaf ) or Internet ( Nats Cloud ).

just exploring options :) 

what ya think ?

**Comment by richardartoul** [comment]
So interestingly I think the abstraction I want baked into NOLA is a blob storage abstraction not a filesystem abstraction. I was planning on adding that but have not found time yet. It could still be backed by memory or indexeddb as well.

I like that because I think it’s almost as equally usefully, but it’s a much narrower interface to implement.

What do you think?

**Comment by richardartoul** [comment]
Closing this for now since there is nothing actionable and not planning on doing this anytime soon
